### ISSUE TITLE
[Chore] 초기 개발 환경 세팅

### ISSUE THREAD

**Issue by i-nooo-2** [part4-team9/GlobalNomad#1]
### 초기 기술 스택
- Next.js 15 app router
- TailwindCSS, PostCSS
- React Query v5
- Zustand

### TODO
- [x]  next.js 및 tailwindCSS 설치
- [x]  yarn 설치
- [x]  zustand 설치 및 세팅
    - 예제 store

    - Auto Generating Selectors 패턴 설정
- [x]  tanstack query 설정
- [x]  tailwindCSS 설정
    - postCSS plugin 설정
        - 벤더 프리픽스
- [x]  eslint, prettier, ~~stylelint~~ 설정
- [x]  전역 스타일링 설정
    - [x]  컬러 시스템
    - [x]  [폰트](https://tailwindcss.com/docs/font-family)
        - [pretendard repo](https://github.com/orioncactus/pretendard)
        - [tailwindCSS font weight](https://tailwindcss.com/docs/font-weight)
            - font-bold : 700
            - font-normal : 400
        - [tailwindCSS font size](https://tailwindcss.com/docs/font-size)
- [x]  test 환경 설정 (jest)
